apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3-vn
          image: acrmslab.azurecr.io/app3/acr-app3:v1 # Update Image Name 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: acr-sp-demo-mslab-secret
# To schedule pods on Azure Virtual Nodes            
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
