apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrmslab-deployment
  labels:
    app: acrmslab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrmslab
  template:
    metadata:
      labels:
        app: acrmslab
    spec:
      containers:
        - name: acrmslab
          image: acrmslab.azurecr.io/app2/acr-app2:v1   # Update Image Name 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: acr-sp-demo-mslab-secret

