apiVersion: v1
kind: Service
metadata:
  name: acrmslab-loadbalancer-service
  labels:
    app: acrmslab
spec:
  type: LoadBalancer
  selector:
    app: acrmslab
  ports:
    - port: 80
      targetPort: 80
